baseurl = "http://tuttieee.com/asha-fusion/"
languageCode = "ja-jp"
title = "ASHA fusion"
canonifyurls = true

[Params]
    googleAnalytics = "UA-78099028-1"
    hideServicesLink = true

#[[Params.social]]
#    title = "facebook"
#    icon = "facebook"
#    url = "https://www.facebook.com/ashafusion/"
